language: node_js

node_js:
  - 10

script:
  - npm run build


after_success: 'npm run coveralls'
# after_success:
#   - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  yarn: true
  directories:
    - node_modules
